name: generate animation SNK

on:
  schedule:
    - cron: "0 */24 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: DoreenHou
          svg_out_path: dist/snake.svg
          palette: github-light # 設定為 light 主題

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
